- name: setup python3 environment
  block:
    - name: add deadsnakes PPA APT repository
      apt_repository:
        repo: ppa:deadsnakes/ppa

    - name: apt install python3 & pip3
      apt:
        name: 
          - python3-pip
          - python3.6
        update_cache: yes

    - name: pip install vital python packages
      pip:
        name: 
          - setuptools
          - virtualenv
          - pipenv
  become: yes
