- name: apt update & upgrade
  ansible.builtin.apt:
    update_cache: yes
    upgrade: full

- name: install vital packages
  ansible.builtin.apt:
    name: 
      - software-properties-common
      - ecryptfs-utils
      - cryptsetup
      - vim
      - tmux
      - curl
      - git
      - cifs-utils      # mount.cifs (NFS)
      - net-tools       # netstat
      - network-manager-openvpn
      - nmap
      - sip-py3api-12.3
      - htop
      - atop
      - xclip
      - ffmpeg          # Firefox video codec
      - thunderbird
      # Python
      - python3
      - python3-pip