---
- name: install apt-transport-https
  apt:
    name:
      - apt-transport-https
      - ca-certificates
  become: yes

- name: add apt docker key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution|lower }}/gpg

- name: add apt docker repository
  become: yes
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution|lower }} {{ ansible_distribution_release }} stable"

- name: install docker
  become: yes
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python3-pip
  notify: restart docker

- name: install docker lib for Ansible
  become: yes
  pip:
    name: docker
    executable: pip3
